CREATE TABLE IF NOT EXISTS public.messages(
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NULL DEFAULT now(),
  message text NULL,
  user_id uuid NULL,
  CONSTRAINT messages_pkey PRIMARY KEY (id)
)
TABLESPACE pg_default;

